### ISSUE TITLE
fatal: pathspec 'other/*.json' did not match any files

### ISSUE THREAD

**Issue by dewey** [lokalise/lokalise-pull-action#10]
Hey—

I'm running the following GitHub Action and I'm running into the error below. The keys on Lokalise have a file assigned, and the "other" and "web" folder were created in my repository.

Do you have a pointer on where it's going wrong there?

Thanks!

```
Switched to a new branch 'lok_active_ffde7f_1739979125'
fatal: pathspec 'other/*.json' did not match any files
Error: failed to add files: exit status 128
Error: commit_changes script failed with exit code 1
```

![Image](https://github.com/user-attachments/assets/854345ec-fdba-4638-8e4c-f1b65c358e73)

```
      - name: Pull from Lokalise
        id: lokalise-pull
        uses: lokalise/lokalise-pull-action@v3.2.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: <redacted>
          base_lang: "en"
          translations_path: |
            web
            other
          file_format: "json"
          always_pull_base: "true"
          flat_naming: "true"
```

![Image](https://github.com/user-attachments/assets/7eb0bb1c-522d-460a-b8a7-dae41039edb3)
