### ISSUE TITLE
Not compatible with json_structured file format

### ISSUE THREAD

**Issue by kislyuk** [lokalise/lokalise-pull-action#11]
Hello,

We are using the json_structured file format for one of our projects. It appears that this GHA is not compatible with that format? When specifying file_format=json_structured, it correctly uses the given value as an API argument to download the files from lokalise, but then proceeds to filter all changed files in git by the glob `*.json_structured`, which is the wrong thing to do. It should filter by `*.json` just as it does for file_format=json.

**Comment by kislyuk** [comment]
Location where the filtering is excluding all the changed files and failing to pull any changes for us:

https://github.com/lokalise/lokalise-pull-action/blob/main/src/detect_changed_files/main.go#L143

**Comment by kislyuk** [comment]
I ran `git status` in my workflow after running this GHA. Here is the output:
```
On branch akislyuk/remove-and-replace-lokalise-workflow
Your branch is up to date with 'origin/akislyuk/remove-and-replace-lokalise-workflow'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/projects/home/frontend/src/ui/translations/languages/am/home.json
	modified:   src/projects/home/frontend/src/ui/translations/languages/ar/home.json
	modified:   src/projects/home/frontend/src/ui/translations/languages/de/home.json
	modified:   src/projects/home/frontend/src/ui/translations/languages/el/home.json
	modified:   src/projects/home/frontend/src/ui/translations/languages/en/home.json
...
	modified:   src/projects/home/frontend/src/ui/translations/languages/zh_Hans/home.json
	modified:   src/projects/home/frontend/src/ui/translations/languages/zh_Hant/home.json
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bin/
```
As you can see, the files are successfully getting downloaded and tracked as changed by git, but then they are getting filtered out instead of staging changes into a PR as expected.

**Comment by kislyuk** [comment]
Full log of GHA configuration:
```
Run lokalise/lokalise-pull-action@v3.2.0
  with:
    pr_labels: ***
    api_token: ***
    project_id: ***
    file_format: json_structured
    base_lang: en
    translations_path: src/projects/home/frontend/src/ui/translations/languages
  
    additional_params: --export-sort a_z --export-empty-as empty --indentation 2sp --add-newline-eof
    skip_include_tags: true
    temp_branch_prefix: lok
    always_pull_base: false
    flat_naming: false
    max_retries: 3
    sleep_on_retry: 1
    download_timeout: 120
```
