### ISSUE TITLE
No changes detected in translation files.

### ISSUE THREAD

**Issue by kyesildagli** [lokalise/lokalise-pull-action#19]
Hi,

I have a flat file structure, where the .json files are in messages/en-GB.json and so on.
I've tried running this action from main and branch. I've renamed my translation key files to messages/%LANG_ISO%.json

![Image](https://github.com/user-attachments/assets/03f9d07f-1c2f-4a08-870e-831b2847bbe1)

i've also tried these: 
![Image](https://github.com/user-attachments/assets/cf0f5bf4-93f0-45f8-83c9-222b88f2919b)

And also tried: messages.%LANG_ISO%.json  and messages_%LANG_ISO%.json notation.
- removed parameter language-mapping and ran, no changes
- Actions have correct read/write permissions and pr create/approve perms.

Downloading translation files from Lokalise...
Starting download from Lokalise
Attempt 1 of 3
Successfully downloaded files.
Download complete! Detecting changed files...
No changes detected in translation files.

Here is the workflow:
```
name: Pull from Lokalise

on:
  pull_request:

jobs:
  pull-lokalise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v3.8.2
        with:
          api_token: ${{ secrets.LOKALISE_API_KEY }}
          project_id: ---
          base_lang: en_GB
          translations_path: messages
          skip_original_filenames: true
          skip_include_tags: true
          flat_naming: true
          file_format: json
          additional_params: |
            --indentation=2sp
            --export-sort=a_z
            --replace-breaks=false
            --language-mapping=[{"original_language_iso":"ar_AR","custom_language_iso":"ar-AR"},{"original_language_iso":"bn_BD","custom_language_iso":"bn-BD"},{"original_language_iso":"de_DE","custom_language_iso":"de-DE"},{"original_language_iso":"en_CA","custom_language_iso":"en-CA"},{"original_language_iso":"en_GB","custom_language_iso":"en-GB"},{"original_language_iso":"en_US","custom_language_iso":"en-US"},{"original_language_iso":"en","custom_language_iso":"en"},{"original_language_iso":"es_ES","custom_language_iso":"es-ES"},{"original_language_iso":"fa_IR","custom_language_iso":"fa-IR"},{"original_language_iso":"fr_CA","custom_language_iso":"fr-CA"},{"original_language_iso":"fr_FR","custom_language_iso":"fr-FR"},{"original_language_iso":"hi_IN","custom_language_iso":"hi-IN"},{"original_language_iso":"id_ID","custom_language_iso":"id-ID"},{"original_language_iso":"ms_MY","custom_language_iso":"ms-MY"},{"original_language_iso":"nl_NL","custom_language_iso":"nl-NL"},{"original_language_iso":"tr_TR","custom_language_iso":"tr-TR"},{"original_language_iso":"ur_PK","custom_language_iso":"ur-PK"}]

```
