### ISSUE TITLE
Add option to set GitHub label on created Pull Request (Enable Auto-Merge)

### ISSUE THREAD

**Issue by dewey** [lokalise/lokalise-pull-action#6]
Hey—

We would like to automatically merge the Pull Requests created by this Action. Would it be possible to add a `pull_request_labels` (Accepting multiple labels) configuration option so that something like [Merge pull requests (automerge-action)](https://github.com/marketplace/actions/merge-pull-requests-automerge-action) could be used to automatically merge them?

Alternatively, there could also be an `auto_merge_pull_request: true` flag that uses [this API option](https://github.com/orgs/community/discussions/24719) to enable auto-merge on the GitHub side.

What do you think?

**Comment by bodrovis** [comment]
Good day! I'll need to research this, hopefully in the next 1-2 days

**Comment by bodrovis** [comment]
So, this feature is implemented here https://github.com/lokalise/lokalise-pull-action/pull/7 so you can test it via the `custom_labels` branch (we'll release a new version in the next few days). However, after doing some testing with the automerge action, I found out that the implementation is not exactly straightforward. It seems that when the automerge action is "just executed" it tries to fetch PRs based on a wrong ref (which seems like a bug).

Perhaps there's a better solution but in my demo project I ended up running automerge on demand. For example, suppose we have this step:

```yaml
- name: Pull from Lokalise
id: lokalise-pull
uses: lokalise/lokalise-pull-action@custom_labels
with:
api_token: ${{ secrets.LOKALISE_API_TOKEN }}
project_id: my_project_id
translations_path: |
  locales
  i18n
base_lang: en
file_format: json
additional_params: "--indentation 2sp --placeholder-format icu"
always_pull_base: true
flat_naming: true
skip_include_tags: true
pr_labels: 'automerge,sample'
```

Then one of the next steps would be:

```yaml
- name: Trigger Automerge Workflow
  if: steps.lokalise-pull.outputs.created_branch != '' && steps.lokalise-pull.outputs.pr_created == 'true'
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.PAT_TOKEN }}
    script: |
      await github.rest.actions.createWorkflowDispatch({
        owner: context.repo.owner,
        repo: context.repo.repo,
        workflow_id: "automerge.yml",
        ref: "${{ steps.lokalise-pull.outputs.created_branch }}",
      });
```

So if the PR was created, we pass the proper ref to the workflow. Then, inside the `automerge.yml` workflow simply do this:

```yaml
name: Automerge PRs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Automerge PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          MERGE_DELETE_BRANCH: "true"
```

Adjust it further as needed.

**Comment by emschenn** [comment]
hi, I was wondering or if it’s possible for `lokalise/lokalise-pull-action` to provide the ID of created PR as an output? Then we can probably use `actions/github-script` to call [enablePullRequestAutoMerge](https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge) on demand?

**Comment by bodrovis** [comment]
Good day! Yeah, I've opened a new issue to look into it https://github.com/lokalise/lokalise-pull-action/issues/6

**Comment by bodrovis** [comment]
This is now live in version 3.2.0. Also we provide information about PR in the outputs (including branch name, ID, and number) https://github.com/lokalise/lokalise-pull-action?tab=readme-ov-file#outputs

**Comment by dewey** [comment]
@emschenn Did you manage to get this to run with `actions/github-script`? Would you be able to share the snippet you are using?

Thanks!

**Comment by emschenn** [comment]
Eventually we’ve decided to merge the PR directly into `main` without a CI check and then run the CI check on `main` to identify and fix any issues...:p  The reason is this allows us to consolidate everything into `main` and run the CI once to get notifications if something goes wrong.

So here's what our workflow looks like:
```
- name: Pull from Lokalise
  uses: lokalise/lokalise-pull-action@v3.2.0
  id: lokalise-pull
  with:
    # skip ....
- name: Merge PR
  if: steps.lokalise-pull.outputs.pr_created == 'true'
  run: gh pr merge --merge "${{ steps.lokalise-pull.outputs.pr_number }}"
  env:
    GH_TOKEN: ${{ github.token }}
```

I'm not sure if using `gh pr merge --auto` ([docs](https://cli.github.com/manual/gh_pr_merge)) will work for achieving auto-merge. Perhaps can give it a try?
